baseURL = "https://klayu.github.io/t2/"
languageCode = "en-us"
title = "BLOG : t2"
theme = "ananke"
publishDir = "public"
[permalinks]
  posts = "/:filename"
enableRobotsTXT = true
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
