baseURL = "https://www.relaxedincome.com"
languageCode = "en-us"
title = "Relaxed Income"
theme = "ananke"
publishDir = "public"
[permalinks]
  posts = "/:filename"
enableRobotsTXT = true
googleAnalytics = "G-G1TTB1QKFD"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
